language: zh

pipeline:
  - name: "rasa_paddlenlp.nlu.paddlenlp_tokenizer.PaddleNLPTokenizer"
    model_name: bert
    model_weights: bert-wwm-ext-chinese
    # Flag to check whether to split intents
    intent_tokenization_flag: false
    # Symbol on which intent should be split
    intent_split_symbol: "_"
  - name: "rasa_paddlenlp.nlu.paddlenlp_featurizer.PaddleNLPFeaturizer"
    model_name: bert
    model_weights: bert-wwm-ext-chinese
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 7
  - name: "DIETClassifier"
    epochs: 100
  - name: "EntitySynonymMapper"
