name: Train and Build

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
  # run it during pull request
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/wechaty/bot5-rasa-nlu:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
