name: Train and Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/wechaty/bot5-rasa-nlu:latest
          cache-from: type=registry,ref=ghcr.io/wechaty/bot5-rasa-nlu:buildcache
          cache-to: type=registry,ref=ghcr.io/wechaty/bot5-rasa-nlu:buildcache,mode=max
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}